### ISSUE TITLE
Strange gap between children (about 900px gap)

### ISSUE THREAD

**Issue by cjke** [netcell/phaser-inspector#1]
![screenshot 2015-09-15 19 47 41](https://cloud.githubusercontent.com/assets/884065/9874678/b68c70d6-5be2-11e5-885c-0b60259ff351.png)

It seems to be related to the style on .fa

```
.phaser-inspector-panel #tree .scene .view .row .middle .toggle .fa {
    width: 100%;
    /* height: 100%; // <-- remove this line and it returns to normal */ 
}
```

**Comment by netcell** [comment]
This is wierd. I'll look into it. Can you provide me with the information regarding your OS, Browser, browser version?

**Comment by cjke** [comment]
Sure sure. I am using OSX + Chrome latest. Two items in the scene, both added to the scene manually

**Comment by netcell** [comment]
Sadly I have not been able to reproduce the problem on my Mac. However, since removing the line doesn't affect the style, I'll be removing it in the next commit :)
