### ISSUE TITLE
Problem with i18next.js

### ISSUE THREAD

**Issue by lukaMis** [netcell/phaser-inspector#2]
Hi

I tried to use plugin in my project but it has an issue with localization library that i use (http://i18next.com/)
If i include this plugin i get following error in console:
Uncaught TypeError: $(...).i18n is not a function

**Comment by netcell** [comment]
Could you upload a screenshot of the console.

**Comment by lukaMis** [comment]
![image](https://cloud.githubusercontent.com/assets/1482793/10214722/25cc53fa-681b-11e5-95f2-499e1e0bab12.png)

![image](https://cloud.githubusercontent.com/assets/1482793/10214734/361d2694-681b-11e5-9294-5e82d57182c5.png)

**Comment by netcell** [comment]
Hi, sorry that I wasn't available to help you before. Currently, this plugin is using angular.js and I found out how ugly it could be regarding performance and I'll be involved with some phaser projects in the upcoming months so I'll be redesign and restructure this plugin.
